version: '3.9'

services:
  scrapyrealstate:
    image: ghcr.io/jrmougan/scrapyrealestate:latest
    container_name: scrapyrealstate
    ports:
      - 8080:8080

    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #network_mode: host